#! /bin/sh

sxhkd &
picom &
xrandr --output VGA1 --auto --same-as LVDS1 --mode 1920x1080
xrandr --output VGA1 --auto --right-of LVDS1
feh --bg-scale ~/Pictures/girl.jpg &
$HOME/.config/polybar/launch.sh

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor LVDS1 -d I II III IV
bspc monitor VGA1 -d V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
